#
# Try to find GLEW library and include path.
# Once done this will define
#
# GLEW_FOUND
# GLEW_INCLUDE_PATH
# GLEW_LIBRARY

FIND_PATH(GLEW_INCLUDE_PATH GL/
	${PROJECT_SOURCE_DIR}/lib/glew/include/
)

FIND_LIBRARY(GLEW_LIBRARY
	NAMES
		libGLEW.a # OS X
	PATHS
		${PROJECT_SOURCE_DIR}/lib/glfw/osx/
)

SET(GLEW_FOUND "NO")
IF (GLEW_INCLUDE_PATH AND GLEW_LIBRARY)
	SET(GLEW_INCLUDE_PATH ${GLEW_INCLUDE_PATH})
	SET(GLEW_LIBRARY ${GLEW_LIBRARY})
	SET(GLEW_FOUND "YES")
ENDIF (GLEW_INCLUDE_PATH AND GLEW_LIBRARY)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLEW_STATIC DEFAULT_MSG GLEW_LIBRARY GLEW_INCLUDE_PATH)
